name: CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: 设置 JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        
    - name: 构建Maven项目
      run: mvn clean package -DskipTests
      
    - name: 上传构建产物
      uses: actions/upload-artifact@v3
      with:
        name: built-jar
        path: target/*.jar

    - name: 列出构建产物目录内容
      run: ls -la target/

  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    
    - name: 下载构建产物
      uses: actions/download-artifact@v3
      with:
        name: built-jar
        path: ./artifact

    - name: 列出下载的构建产物目录内容
      run: ls -la ./artifact/

    - name: 创建 Release
      uses: softprops/action-gh-release@v2
      with:
        files: ./artifact/*.jar
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: 检查 GITHUB_TOKEN 权限
      run: |
        echo "验证 GITHUB_TOKEN 权限..."
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/releases