name: BuildandPackageArtifacts

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

jobs:
  job1:
    name: BuildandUploadJAR
    runs-on: ubuntu-latest
    outputs:
      jar_path: ${{ steps.upload_jar.outputs.upload-url }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn clean install
      - name: Find and Copy JAR artifact
        id: find_jar
        run: |
          set -x
          JAR_PATH=$(find target -name "*.jar")
          cp "$JAR_PATH" target/app.jar
          echo "JAR_PATH=target/app.jar" >> $GITHUB_OUTPUT
      - name: Upload JAR
        id: upload_jar
        uses: actions/upload-artifact@v3
        with:
          name: app.jar
          path: ${{ steps.find_jar.outputs.JAR_PATH }}

  job2:
    name: PackageARM64Artifact
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: app.jar
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Create application image with jpackage (ARM64)
        run: |
          set -x
          jpackage \
            --name my-app-arm64 \
            --verbose \
            --description "My Spring Boot Application (ARM64)" \
            --vendor "My Company" \
            --input . \
            --main-jar "app.jar" \
            --dest output-arm64

      - name: Upload ARM64 Package Artifact
        uses: actions/upload-artifact@v3
        with:
          name: arm64-package
          path: output-arm64
