name: CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: 设置 JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        
    - name: 构建Maven项目
      run: mvn clean package -DskipTests
      
    - name: 上传构建产物
      uses: actions/upload-artifact@v3
      with:
        name: built-jar
        path: target/*.jar

    - name: 列出构建产物目录内容
      run: ls -la target/

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        arch: [x64, aarch64]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    
    - name: 设置 JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: 下载构建产物
      uses: actions/download-artifact@v3
      with:
        name: built-jar
        path: ./

    - name: 获取 JAR 文件名
      run: |
        JAR_FILE=$(find . -name "*.jar" -print -quit)
        echo "JAR_FILE=$JAR_FILE" >> $GITHUB_ENV

    - name: 打包应用程序 - ${{ matrix.os }} ${{ matrix.arch }}
      run: |
        VENDOR="YourVendor" # 将 "YourVendor" 替换为你的供应商名称
        APP_NAME="YourAppName" # 将 "YourAppName" 替换为你的应用名称
        APP_VERSION=$(echo "${GITHUB_REF#refs/tags/}")

        case "${{ matrix.os }}" in
          windows-latest)
            EXT="exe"
            if [[ "${{ matrix.arch }}" == "x64" ]]; then
              ARCH_FLAG="--win-x64-bundler"
            else
              ARCH_FLAG="--win-arm64-bundler"
            fi
            ;;
          ubuntu-latest)
            EXT="deb"
            if [[ "${{ matrix.arch }}" == "x64" ]]; then
              ARCH_FLAG="--linux-deb-package"
            else
              ARCH_FLAG="--linux-arm64-package"
            fi
            ;;
          macos-latest)
            EXT="pkg"
            if [[ "${{ matrix.arch }}" == "x64" ]]; then
              ARCH_FLAG="--mac-pkg-identifier com.${VENDOR}.${APP_NAME}"
            else
              ARCH_FLAG="--mac-package-identifier com.${VENDOR}.${APP_NAME}"
            fi
            ;;
        esac

        jpackage \
          --dest "build" \
          --type "${EXT}" \
          --app-version "${APP_VERSION}" \
          --vendor "${VENDOR}" \
          --name "${APP_NAME}" \
          --input . \
          --main-jar "${{ env.JAR_FILE }}" \
          --main-class com.example.githu_bworkflow.GithubWorkflowApplication # 替换为你的主类名
          ${ARCH_FLAG}

    - name: 上传打包好的应用程序 - ${{ matrix.os }} ${{ matrix.arch }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-${{ matrix.arch }}-packages
        path: release/build