name: Build and Package ARM64 Artifact

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven for ARM64
        run: mvn clean install -DtargetArchitecture=arm64
      - name: Find JAR artifact
        id: find_jar
        run: |
          JAR_PATH=$(find target -name "*.jar")
          echo "JAR_PATH=$JAR_PATH" >> $GITHUB_OUTPUT
          FILENAME=$(basename "$JAR_PATH")
          echo "FILENAME=$FILENAME" >> $GITHUB_OUTPUT
      - name: Create application image with jpackage
        run: |
          jpackage \
            --name my-app-arm64 \
            --description "My Spring Boot Application (ARM64)" \
            --vendor "My Company" \
            --input target/ \
            --main-jar ${{ steps.find_jar.outputs.FILENAME }} \
            --dest build/install
      - name: Find package artifact
        id: find_package
        run: |
          PACKAGE_PATH=$(find build/install -type f)
          echo "PACKAGE_PATH=$PACKAGE_PATH" >> $GITHUB_OUTPUT
      - name: Upload Package Artifact
        uses: actions/upload-artifact@v3
        with:
          name: arm64-package
          path: ${{ steps.find_package.outputs.PACKAGE_PATH }}
