name: BuildandPackageArtifacts

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

jobs:
  job1:
    name: BuildandUploadJAR
    runs-on: ubuntu-latest
    outputs:
      jar_path: ${{ steps.upload_jar.outputs.upload-url }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean install
      - name: Find JAR artifact
        id: find_jar
        run: |
          JAR_PATH=$(find target -name "*.jar")
          echo "JAR_PATH=$JAR_PATH" >> $GITHUB_OUTPUT
      - name: Upload JAR
        id: upload_jar
        uses: actions/upload-artifact@v3
        with:
          name: app.jar
          path: ${{ steps.find_jar.outputs.JAR_PATH }}

  job2:
    name: PackageARM64Artifact
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: app.jar
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Create application image with jpackage (ARM64)
        run: |
          set -x
          find . -name "app.jar"
            jpackage \
            --name my-app-arm64 \
            --verbose \
            --description "My Spring Boot Application (ARM64)" \
            --vendor "My Company" \
            --input . \
            --main-jar "/home/runner/work/BuildandPackage Artifacts/euoggu/test_github_workflow/app.jar" \
            --dest output-arm64

      - name: Upload ARM64 Package Artifact
        uses: actions/upload-artifact@v3
        with:
          name: arm64-package
          path: output-arm64

  job3:
    name: Package AMD64 Artifact
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: app.jar
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Create application image with jpackage (AMD64)
        run: |
          set -x
          jpackage \
            --name my-app-amd64 \
            --verbose \
            --description "My Spring Boot Application (AMD64)" \
            --vendor "My Company" \
            --input /home/runner/work/test_github_workflow/test_github_workflow \
            --main-jar app.jar \
            --dest output-amd64
      - name: Upload AMD64 Package Artifact
        uses: actions/upload-artifact@v3
        with:
          name: amd64-package
          path: output-amd64
