name: CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: 设置 JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        
    - name: 构建Maven项目
      run: mvn clean package -DskipTests
      
    - name: 列出构建产物目录内容
      run: ls -la target/

    - name: 上传构建产物
      uses: actions/upload-artifact@v3
      with:
        name: built-jar
        path: target/*.jar

  release-windows-x64:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: 设置 JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: 下载构建产物
      uses: actions/download-artifact@v3
      with:
        name: built-jar
        path: ./
    - name: 获取 JAR 文件名
      run: |
        JAR_FILE=$(find . -name "*.jar" -print -quit)
        echo "JAR_FILE=$JAR_FILE" >> $GITHUB_ENV
    - name: 打包应用程序 - Windows x64
      run: |
        VENDOR="MyCompany"
        APP_NAME="MyApp"
        APP_VERSION=$(echo "${GITHUB_REF#refs/tags/}")
        jpackage --dest "build" --type "exe" --app-version "${APP_VERSION}" --vendor "${VENDOR}" --name "${APP_NAME}" --input . --main-jar "$JAR_FILE" --main-class com.example.githu_bworkflow.GithubWorkflowApplication --win-x64-bundler
    - name: 上传打包好的应用程序 - Windows x64
      uses: actions/upload-artifact@v3
      with:
        name: windows-x64-package
        path: build

  release-windows-arm64:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: 设置 JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: 下载构建产物
      uses: actions/download-artifact@v3
      with:
        name: built-jar
        path: ./
    - name: 获取 JAR 文件名
      run: |
        JAR_FILE=$(find . -name "*.jar" -print -quit)
        echo "JAR_FILE=$JAR_FILE" >> $GITHUB_ENV
    - name: 打包应用程序 - Windows arm64
      run: |
        VENDOR="MyCompany"
        APP_NAME="MyApp"
        APP_VERSION=$(echo "${GITHUB_REF#refs/tags/}")
        jpackage --dest "build" --type "exe" --app-version "${APP_VERSION}" --vendor "${VENDOR}" --name "${APP_NAME}" --input . --main-jar "$JAR_FILE" --main-class com.example.githu_bworkflow.GithubWorkflowApplication --win-arm64-bundler
    - name: 上传打包好的应用程序 - Windows arm64
      uses: actions/upload-artifact@v3
      with:
        name: windows-arm64-package
        path: build

  release-linux-x64:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: 设置 JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: 下载构建产物
      uses: actions/download-artifact@v3
      with:
        name: built-jar
        path: ./
    - name: 获取 JAR 文件名
      run: |
        JAR_FILE=$(find . -name "*.jar" -print -quit)
        echo "JAR_FILE=$JAR_FILE" >> $GITHUB_ENV
    - name: 打包应用程序 - Linux x64
      run: |
        VENDOR="MyCompany"
        APP_NAME="MyApp"
        APP_VERSION=$(echo "${GITHUB_REF#refs/tags/}")
        jpackage --dest "build" --type "deb" --app-version "${APP_VERSION}" --vendor "${VENDOR}" --name "${APP_NAME}" --input . --main-jar "$JAR_FILE" --main-class com.example.githu_bworkflow.GithubWorkflowApplication --linux-deb-package
    - name: 上传打包好的应用程序 - Linux x64
      uses: actions/upload-artifact@v3
      with:
        name: linux-x64-package
        path: build

  release-linux-arm64:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: 设置 JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: 下载构建产物
      uses: actions/download-artifact@v3
      with:
        name: built-jar
        path: ./
    - name: 获取 JAR 文件名
      run: |
        JAR_FILE=$(find . -name "*.jar" -print -quit)
        echo "JAR_FILE=$JAR_FILE" >> $GITHUB_ENV
    - name: 打包应用程序 - Linux arm64
      run: |
        VENDOR="MyCompany"
        APP_NAME="MyApp"
        APP_VERSION=$(echo "${GITHUB_REF#refs/tags/}")
        jpackage --dest "build" --type "deb" --app-version "${APP_VERSION}" --vendor "${VENDOR}" --name "${APP_NAME}" --input . --main-jar "$JAR_FILE" --main-class com.example.githu_bworkflow.GithubWorkflowApplication --linux-arm64-package
    - name: 上传打包好的应用程序 - Linux arm64
      uses: actions/upload-artifact@v3
      with:
        name: linux-arm64-package
        path: build

  release-macos-x64:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: 设置 JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: 下载构建产物
      uses: actions/download-artifact@v3
      with:
        name: built-jar
        path: ./
    - name: 获取 JAR 文件名
      run: |
        JAR_FILE=$(find . -name "*.jar" -print -quit)
        echo "JAR_FILE=$JAR_FILE" >> $GITHUB_ENV
    - name: 打包应用程序 - macOS x64
      run: |
        VENDOR="MyCompany"
        APP_NAME="MyApp"
        APP_VERSION=$(echo "${GITHUB_REF#refs/tags/}")
        MAC_APP_VERSION=$(echo "${APP_VERSION}" | sed 's/^v//' | sed 's/\([0-9]\{4\}\)\([0-9]\{2\}\)\([0-9]\{2\}\).*/\1.\2.\3/')
        jpackage --dest "build" --type "pkg" --app-version "${MAC_APP_VERSION}" --vendor "${VENDOR}" --name "${APP_NAME}" --input . --main-jar "$JAR_FILE" --main-class com.example.githu_bworkflow.GithubWorkflowApplication --mac-package-identifier com.${VENDOR}.${APP_NAME}
    - name: 上传打包好的应用程序 - macOS x64
      uses: actions/upload-artifact@v3
      with:
        name: macos-x64-package
        path: build

  release-macos-arm64:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: 设置 JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: 下载构建产物
      uses: actions/download-artifact@v3
      with:
        name: built-jar
        path: ./
    - name: 获取 JAR 文件名
      run: |
        JAR_FILE=$(find . -name "*.jar" -print -quit)
        echo "JAR_FILE=$JAR_FILE" >> $GITHUB_ENV
    - name: 打包应用程序 - macOS arm64
      run: |
        VENDOR="MyCompany"
        APP_NAME="MyApp"
        APP_VERSION=$(echo "${GITHUB_REF#refs/tags/}")
        MAC_APP_VERSION=$(echo "${APP_VERSION}" | sed 's/^v//' | sed 's/\([0-9]\{4\}\)\([0-9]\{2\}\)\([0-9]\{2\}\).*/\1.\2.\3/')
        jpackage --dest "build" --type "pkg" --app-version "${MAC_APP_VERSION}" --vendor "${VENDOR}" --name "${APP_NAME}" --input . --main-jar "$JAR_FILE" --main-class com.example.githu_bworkflow.GithubWorkflowApplication --mac-package-identifier com.${VENDOR}.${APP_NAME}
    - name: 上传打包好的应用程序 - macOS arm64
      uses: actions/upload-artifact@v3
      with:
        name: macos-arm64-package
        path: build