name: Build and Release

on:
  push:
    tags:
      - 'v*' # 当推送带v开头的tag时触发，如 v1.0.0

# 添加权限配置
permissions:
  contents: write # 添加写入权限

jobs:
  build:
    runs-on: windows-latest # 使用 Windows 运行环境
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Package with jpackage
        shell: cmd
        run: |
          jpackage --input target/ ^
          --dest target/dist ^
          --name YourAppName ^
          --main-jar githu_bworkflow-0.0.1-SNAPSHOT.jar ^
          --type exe ^
          --win-shortcut ^
          --win-menu

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/dist/*.exe
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}